### ISSUE TITLE
InputNodeName and textAreaNodeName ca use value in _getElementValue

### ISSUE THREAD

**Issue by Ccastillo06** [shystruk/bind-dom#1]
The code that getting the value of these element is swapped:

```
function _getElementValue(node) {
    if (
          node.nodeName === inputNodeName
          node.nodeName === textAreaNodeName
    ) { 
        return node.value;
    }

    return node.textContent;
}
```

Hope this helps! 👍🏻

**Comment by shystruk** [comment]
Hi @Ccastillo06 
Thank you for being interested in.
For input we set attribute value, for textarea we set value to the node obect not to the DOM element as content may be huge. Please check examples on README :)
```jacascript
function _setElementValue(node, value) {
    if (node.nodeName === inputNodeName) {
        node.setAttribute('value', value);
    } else if (node.nodeName === textAreaNodeName) {
        node.value = value;
    } else {
        node.innerHTML = value;
    }
}
```

**Comment by Ccastillo06** [comment]
I just updated after testing a bit more, for your examples is good like that! Didn't notice that we wanted the node value in there after debugging! 

Great example man!

**Comment by shystruk** [comment]
MutationObserver works only with DOM changes (attributes, content), so when you change something to your observer (element) make sure that something is changed in the DOM :)

**Comment by shystruk** [comment]
@Ccastillo06 example with React you may find here https://github.com/shystruk/create-react-redux-app-structure :) 
Page - Components Communication
